<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OC.Bootstrapper.Shared\OC.Bootstrapper.Shared.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\OC.BuildingBlocks.SharedKernel\OC.BuildingBlocks.SharedKernel.csproj" />
  </ItemGroup>

</Project>
