.PHONY: install run build lint format preview clean

install:
	pnpm install

run:
	pnpm run dev

build:
	pnpm run build

lint:
	pnpm run lint

format:
	pnpm run format

preview:
	pnpm run preview

clean:
	pnpm run build --clean
	rm -rf dist node_modules
